# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 33ef24d4fc2479b7f9ea1e9b0ff09e5683c198855538b2273371df7248455e0a1626f47c0b1543f57a3df4b4c1f1fe18910db75019cadf83b8fd3858fb3746ce

test:
  secret_key_base: 19322b5b021104416a3f469268e5fde91777ae57c3619a7b84841670b4cce57d2fc498eda178be48351292ae33ebcfb2cfd932bc0ec0cca340d68df417ac2979

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
